'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace LotizadorService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CompositeType", [Namespace]:="http://schemas.datacontract.org/2004/07/Lotizador.WCF"),  _
     System.SerializableAttribute()>  _
    Partial Public Class CompositeType
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BoolValueField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private StringValueField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BoolValue() As Boolean
            Get
                Return Me.BoolValueField
            End Get
            Set
                If (Me.BoolValueField.Equals(value) <> true) Then
                    Me.BoolValueField = value
                    Me.RaisePropertyChanged("BoolValue")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property StringValue() As String
            Get
                Return Me.StringValueField
            End Get
            Set
                If (Object.ReferenceEquals(Me.StringValueField, value) <> true) Then
                    Me.StringValueField = value
                    Me.RaisePropertyChanged("StringValue")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="LotizadorService.INarhen")>  _
    Public Interface INarhen
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetData", ReplyAction:="http://tempuri.org/INarhen/GetDataResponse")>  _
        Function GetData(ByVal value As Integer) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetData", ReplyAction:="http://tempuri.org/INarhen/GetDataResponse")>  _
        Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/INarhen/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContract(ByVal composite As LotizadorService.CompositeType) As LotizadorService.CompositeType
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetDataUsingDataContract", ReplyAction:="http://tempuri.org/INarhen/GetDataUsingDataContractResponse")>  _
        Function GetDataUsingDataContractAsync(ByVal composite As LotizadorService.CompositeType) As System.Threading.Tasks.Task(Of LotizadorService.CompositeType)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarSocio", ReplyAction:="http://tempuri.org/INarhen/InsertarSocioResponse")>  _
        Function InsertarSocio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarSocio", ReplyAction:="http://tempuri.org/INarhen/InsertarSocioResponse")>  _
        Function InsertarSocioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarSocio", ReplyAction:="http://tempuri.org/INarhen/ActualizarSocioResponse")>  _
        Function ActualizarSocio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarSocio", ReplyAction:="http://tempuri.org/INarhen/ActualizarSocioResponse")>  _
        Function ActualizarSocioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarSocio", ReplyAction:="http://tempuri.org/INarhen/EliminarSocioResponse")>  _
        Function EliminarSocio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarSocio", ReplyAction:="http://tempuri.org/INarhen/EliminarSocioResponse")>  _
        Function EliminarSocioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerSocioPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerSocioPorCriterioResponse")>  _
        Function ObtenerSocioPorCriterio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Lotizador.BE.SocioBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerSocioPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerSocioPorCriterioResponse")>  _
        Function ObtenerSocioPorCriterioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Lotizador.BE.SocioBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerTipoDocumentoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerTipoDocumentoPorCriterioResponse")>  _
        Function ObtenerTipoDocumentoPorCriterio(ByVal oSocioBE As Lotizador.BE.TipoDocumentoBE) As Lotizador.BE.TipoDocumentoBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerTipoDocumentoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerTipoDocumentoPorCriterioResponse")>  _
        Function ObtenerTipoDocumentoPorCriterioAsync(ByVal oSocioBE As Lotizador.BE.TipoDocumentoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.TipoDocumentoBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerVariablePorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerVariablePorCriterioResponse")>  _
        Function ObtenerVariablePorCriterio(ByVal oVariableBE As Lotizador.BE.VariableBE) As Lotizador.BE.VariableBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerVariablePorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerVariablePorCriterioResponse")>  _
        Function ObtenerVariablePorCriterioAsync(ByVal oVariableBE As Lotizador.BE.VariableBE) As System.Threading.Tasks.Task(Of Lotizador.BE.VariableBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetDepartamentos", ReplyAction:="http://tempuri.org/INarhen/GetDepartamentosResponse")>  _
        Function GetDepartamentos() As Lotizador.BE.UbigeoBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetDepartamentos", ReplyAction:="http://tempuri.org/INarhen/GetDepartamentosResponse")>  _
        Function GetDepartamentosAsync() As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetProvincias", ReplyAction:="http://tempuri.org/INarhen/GetProvinciasResponse")>  _
        Function GetProvincias(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetProvincias", ReplyAction:="http://tempuri.org/INarhen/GetProvinciasResponse")>  _
        Function GetProvinciasAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetDistritos", ReplyAction:="http://tempuri.org/INarhen/GetDistritosResponse")>  _
        Function GetDistritos(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetDistritos", ReplyAction:="http://tempuri.org/INarhen/GetDistritosResponse")>  _
        Function GetDistritosAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetUbigeo", ReplyAction:="http://tempuri.org/INarhen/GetUbigeoResponse")>  _
        Function GetUbigeo(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetUbigeo", ReplyAction:="http://tempuri.org/INarhen/GetUbigeoResponse")>  _
        Function GetUbigeoAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetUbigeoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/GetUbigeoPorCriterioResponse")>  _
        Function GetUbigeoPorCriterio(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/GetUbigeoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/GetUbigeoPorCriterioResponse")>  _
        Function GetUbigeoPorCriterioAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarMoneda", ReplyAction:="http://tempuri.org/INarhen/InsertarMonedaResponse")>  _
        Function InsertarMoneda(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarMoneda", ReplyAction:="http://tempuri.org/INarhen/InsertarMonedaResponse")>  _
        Function InsertarMonedaAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarMoneda", ReplyAction:="http://tempuri.org/INarhen/ActualizarMonedaResponse")>  _
        Function ActualizarMoneda(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarMoneda", ReplyAction:="http://tempuri.org/INarhen/ActualizarMonedaResponse")>  _
        Function ActualizarMonedaAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarMoneda", ReplyAction:="http://tempuri.org/INarhen/EliminarMonedaResponse")>  _
        Function EliminarMoneda(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarMoneda", ReplyAction:="http://tempuri.org/INarhen/EliminarMonedaResponse")>  _
        Function EliminarMonedaAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerMonedaPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerMonedaPorCriterioResponse")>  _
        Function ObtenerMonedaPorCriterio(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Lotizador.BE.MonedaBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerMonedaPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerMonedaPorCriterioResponse")>  _
        Function ObtenerMonedaPorCriterioAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Lotizador.BE.MonedaBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarProyecto", ReplyAction:="http://tempuri.org/INarhen/InsertarProyectoResponse")>  _
        Function InsertarProyecto(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarProyecto", ReplyAction:="http://tempuri.org/INarhen/InsertarProyectoResponse")>  _
        Function InsertarProyectoAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarProyecto", ReplyAction:="http://tempuri.org/INarhen/ActualizarProyectoResponse")>  _
        Function ActualizarProyecto(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarProyecto", ReplyAction:="http://tempuri.org/INarhen/ActualizarProyectoResponse")>  _
        Function ActualizarProyectoAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarProyecto", ReplyAction:="http://tempuri.org/INarhen/EliminarProyectoResponse")>  _
        Function EliminarProyecto(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarProyecto", ReplyAction:="http://tempuri.org/INarhen/EliminarProyectoResponse")>  _
        Function EliminarProyectoAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerProyectoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerProyectoPorCriterioResponse")>  _
        Function ObtenerProyectoPorCriterio(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Lotizador.BE.ProyectoBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerProyectoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerProyectoPorCriterioResponse")>  _
        Function ObtenerProyectoPorCriterioAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.ProyectoBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarUnidadCatastral", ReplyAction:="http://tempuri.org/INarhen/InsertarUnidadCatastralResponse")>  _
        Function InsertarUnidadCatastral(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarUnidadCatastral", ReplyAction:="http://tempuri.org/INarhen/InsertarUnidadCatastralResponse")>  _
        Function InsertarUnidadCatastralAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarUnidadCatastral", ReplyAction:="http://tempuri.org/INarhen/ActualizarUnidadCatastralResponse")>  _
        Function ActualizarUnidadCatastral(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarUnidadCatastral", ReplyAction:="http://tempuri.org/INarhen/ActualizarUnidadCatastralResponse")>  _
        Function ActualizarUnidadCatastralAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarUnidadCatastral", ReplyAction:="http://tempuri.org/INarhen/EliminarUnidadCatastralResponse")>  _
        Function EliminarUnidadCatastral(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarUnidadCatastral", ReplyAction:="http://tempuri.org/INarhen/EliminarUnidadCatastralResponse")>  _
        Function EliminarUnidadCatastralAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerUnidadCatastralPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerUnidadCatastralPorCriterioResponse")>  _
        Function ObtenerUnidadCatastralPorCriterio(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Lotizador.BE.UnidadCatastralBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerUnidadCatastralPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerUnidadCatastralPorCriterioResponse")>  _
        Function ObtenerUnidadCatastralPorCriterioAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UnidadCatastralBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarLote", ReplyAction:="http://tempuri.org/INarhen/InsertarLoteResponse")>  _
        Function InsertarLote(ByVal oLoteBE As Lotizador.BE.LoteBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarLote", ReplyAction:="http://tempuri.org/INarhen/InsertarLoteResponse")>  _
        Function InsertarLoteAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarLote", ReplyAction:="http://tempuri.org/INarhen/ActualizarLoteResponse")>  _
        Function ActualizarLote(ByVal oLoteBE As Lotizador.BE.LoteBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarLote", ReplyAction:="http://tempuri.org/INarhen/ActualizarLoteResponse")>  _
        Function ActualizarLoteAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarLote", ReplyAction:="http://tempuri.org/INarhen/EliminarLoteResponse")>  _
        Function EliminarLote(ByVal oLoteBE As Lotizador.BE.LoteBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarLote", ReplyAction:="http://tempuri.org/INarhen/EliminarLoteResponse")>  _
        Function EliminarLoteAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerLotePorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerLotePorCriterioResponse")>  _
        Function ObtenerLotePorCriterio(ByVal oLoteBE As Lotizador.BE.LoteBE) As Lotizador.BE.LoteBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerLotePorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerLotePorCriterioResponse")>  _
        Function ObtenerLotePorCriterioAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Lotizador.BE.LoteBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerLotesDisponibles", ReplyAction:="http://tempuri.org/INarhen/ObtenerLotesDisponiblesResponse")>  _
        Function ObtenerLotesDisponibles(ByVal IdProyecto As String, ByVal IdLote As String) As Lotizador.BE.LoteBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerLotesDisponibles", ReplyAction:="http://tempuri.org/INarhen/ObtenerLotesDisponiblesResponse")>  _
        Function ObtenerLotesDisponiblesAsync(ByVal IdProyecto As String, ByVal IdLote As String) As System.Threading.Tasks.Task(Of Lotizador.BE.LoteBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarSecuencia", ReplyAction:="http://tempuri.org/INarhen/InsertarSecuenciaResponse")>  _
        Function InsertarSecuencia(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarSecuencia", ReplyAction:="http://tempuri.org/INarhen/InsertarSecuenciaResponse")>  _
        Function InsertarSecuenciaAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarSecuencia", ReplyAction:="http://tempuri.org/INarhen/ActualizarSecuenciaResponse")>  _
        Function ActualizarSecuencia(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarSecuencia", ReplyAction:="http://tempuri.org/INarhen/ActualizarSecuenciaResponse")>  _
        Function ActualizarSecuenciaAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarSecuencia", ReplyAction:="http://tempuri.org/INarhen/EliminarSecuenciaResponse")>  _
        Function EliminarSecuencia(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarSecuencia", ReplyAction:="http://tempuri.org/INarhen/EliminarSecuenciaResponse")>  _
        Function EliminarSecuenciaAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerSecuenciaPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerSecuenciaPorCriterioResponse")>  _
        Function ObtenerSecuenciaPorCriterio(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Lotizador.BE.SecuenciaBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerSecuenciaPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerSecuenciaPorCriterioResponse")>  _
        Function ObtenerSecuenciaPorCriterioAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Lotizador.BE.SecuenciaBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarUsuario", ReplyAction:="http://tempuri.org/INarhen/InsertarUsuarioResponse")>  _
        Function InsertarUsuario(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarUsuario", ReplyAction:="http://tempuri.org/INarhen/InsertarUsuarioResponse")>  _
        Function InsertarUsuarioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarUsuario", ReplyAction:="http://tempuri.org/INarhen/ActualizarUsuarioResponse")>  _
        Function ActualizarUsuario(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarUsuario", ReplyAction:="http://tempuri.org/INarhen/ActualizarUsuarioResponse")>  _
        Function ActualizarUsuarioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarPassword", ReplyAction:="http://tempuri.org/INarhen/ActualizarPasswordResponse")>  _
        Function ActualizarPassword(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarPassword", ReplyAction:="http://tempuri.org/INarhen/ActualizarPasswordResponse")>  _
        Function ActualizarPasswordAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarUsuario", ReplyAction:="http://tempuri.org/INarhen/EliminarUsuarioResponse")>  _
        Function EliminarUsuario(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarUsuario", ReplyAction:="http://tempuri.org/INarhen/EliminarUsuarioResponse")>  _
        Function EliminarUsuarioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerUsuarioPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerUsuarioPorCriterioResponse")>  _
        Function ObtenerUsuarioPorCriterio(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Lotizador.BE.UsuarioBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerUsuarioPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerUsuarioPorCriterioResponse")>  _
        Function ObtenerUsuarioPorCriterioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UsuarioBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerUsuarioPorId", ReplyAction:="http://tempuri.org/INarhen/ObtenerUsuarioPorIdResponse")>  _
        Function ObtenerUsuarioPorId(ByVal IdUsuario As Integer) As Lotizador.BE.UsuarioBE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerUsuarioPorId", ReplyAction:="http://tempuri.org/INarhen/ObtenerUsuarioPorIdResponse")>  _
        Function ObtenerUsuarioPorIdAsync(ByVal IdUsuario As Integer) As System.Threading.Tasks.Task(Of Lotizador.BE.UsuarioBE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarBanco", ReplyAction:="http://tempuri.org/INarhen/InsertarBancoResponse")>  _
        Function InsertarBanco(ByVal oBancoBE As Lotizador.BE.BancoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarBanco", ReplyAction:="http://tempuri.org/INarhen/InsertarBancoResponse")>  _
        Function InsertarBancoAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarBanco", ReplyAction:="http://tempuri.org/INarhen/ActualizarBancoResponse")>  _
        Function ActualizarBanco(ByVal oBancoBE As Lotizador.BE.BancoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarBanco", ReplyAction:="http://tempuri.org/INarhen/ActualizarBancoResponse")>  _
        Function ActualizarBancoAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarBanco", ReplyAction:="http://tempuri.org/INarhen/EliminarBancoResponse")>  _
        Function EliminarBanco(ByVal oBancoBE As Lotizador.BE.BancoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarBanco", ReplyAction:="http://tempuri.org/INarhen/EliminarBancoResponse")>  _
        Function EliminarBancoAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerBancoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerBancoPorCriterioResponse")>  _
        Function ObtenerBancoPorCriterio(ByVal oBancoBE As Lotizador.BE.BancoBE) As Lotizador.BE.BancoBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerBancoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerBancoPorCriterioResponse")>  _
        Function ObtenerBancoPorCriterioAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.BancoBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarContrato", ReplyAction:="http://tempuri.org/INarhen/InsertarContratoResponse")>  _
        Function InsertarContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarContrato", ReplyAction:="http://tempuri.org/INarhen/InsertarContratoResponse")>  _
        Function InsertarContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarContrato", ReplyAction:="http://tempuri.org/INarhen/ActualizarContratoResponse")>  _
        Function ActualizarContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarContrato", ReplyAction:="http://tempuri.org/INarhen/ActualizarContratoResponse")>  _
        Function ActualizarContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarContrato", ReplyAction:="http://tempuri.org/INarhen/EliminarContratoResponse")>  _
        Function EliminarContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarContrato", ReplyAction:="http://tempuri.org/INarhen/EliminarContratoResponse")>  _
        Function EliminarContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerContratoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerContratoPorCriterioResponse")>  _
        Function ObtenerContratoPorCriterio(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Lotizador.BE.ContratoBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerContratoPorCriterio", ReplyAction:="http://tempuri.org/INarhen/ObtenerContratoPorCriterioResponse")>  _
        Function ObtenerContratoPorCriterioAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.ContratoBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerContrato", ReplyAction:="http://tempuri.org/INarhen/ObtenerContratoResponse")>  _
        Function ObtenerContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Lotizador.BE.ContratoBE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerContrato", ReplyAction:="http://tempuri.org/INarhen/ObtenerContratoResponse")>  _
        Function ObtenerContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.ContratoBE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/InsertarMonedaTipoCambioResponse")>  _
        Function InsertarMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/InsertarMonedaTipoCambioResponse")>  _
        Function InsertarMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/ActualizarMonedaTipoCambioResponse")>  _
        Function ActualizarMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/ActualizarMonedaTipoCambioResponse")>  _
        Function ActualizarMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/EliminarMonedaTipoCambioResponse")>  _
        Function EliminarMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/EliminarMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/EliminarMonedaTipoCambioResponse")>  _
        Function EliminarMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/ObtenerMonedaTipoCambioResponse")>  _
        Function ObtenerMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Lotizador.BE.MonedaTipoCambioBE()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ObtenerMonedaTipoCambio", ReplyAction:="http://tempuri.org/INarhen/ObtenerMonedaTipoCambioResponse")>  _
        Function ObtenerMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Lotizador.BE.MonedaTipoCambioBE())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/CommandText", ReplyAction:="http://tempuri.org/INarhen/CommandTextResponse")>  _
        Function CommandText(ByVal oGeneralBE As Lotizador.BE.GeneralBE) As Lotizador.BE.GeneralBE
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/CommandText", ReplyAction:="http://tempuri.org/INarhen/CommandTextResponse")>  _
        Function CommandTextAsync(ByVal oGeneralBE As Lotizador.BE.GeneralBE) As System.Threading.Tasks.Task(Of Lotizador.BE.GeneralBE)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ExecuteSQL", ReplyAction:="http://tempuri.org/INarhen/ExecuteSQLResponse")>  _
        Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ExecuteSQL", ReplyAction:="http://tempuri.org/INarhen/ExecuteSQLResponse")>  _
        Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarListaError", ReplyAction:="http://tempuri.org/INarhen/InsertarListaErrorResponse")>  _
        Function InsertarListaError(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/InsertarListaError", ReplyAction:="http://tempuri.org/INarhen/InsertarListaErrorResponse")>  _
        Function InsertarListaErrorAsync(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarListaError", ReplyAction:="http://tempuri.org/INarhen/ActualizarListaErrorResponse")>  _
        Function ActualizarListaError(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/INarhen/ActualizarListaError", ReplyAction:="http://tempuri.org/INarhen/ActualizarListaErrorResponse")>  _
        Function ActualizarListaErrorAsync(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface INarhenChannel
        Inherits LotizadorService.INarhen, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class NarhenClient
        Inherits System.ServiceModel.ClientBase(Of LotizadorService.INarhen)
        Implements LotizadorService.INarhen
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetData(ByVal value As Integer) As String Implements LotizadorService.INarhen.GetData
            Return MyBase.Channel.GetData(value)
        End Function
        
        Public Function GetDataAsync(ByVal value As Integer) As System.Threading.Tasks.Task(Of String) Implements LotizadorService.INarhen.GetDataAsync
            Return MyBase.Channel.GetDataAsync(value)
        End Function
        
        Public Function GetDataUsingDataContract(ByVal composite As LotizadorService.CompositeType) As LotizadorService.CompositeType Implements LotizadorService.INarhen.GetDataUsingDataContract
            Return MyBase.Channel.GetDataUsingDataContract(composite)
        End Function
        
        Public Function GetDataUsingDataContractAsync(ByVal composite As LotizadorService.CompositeType) As System.Threading.Tasks.Task(Of LotizadorService.CompositeType) Implements LotizadorService.INarhen.GetDataUsingDataContractAsync
            Return MyBase.Channel.GetDataUsingDataContractAsync(composite)
        End Function
        
        Public Function InsertarSocio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Boolean Implements LotizadorService.INarhen.InsertarSocio
            Return MyBase.Channel.InsertarSocio(oSocioBE)
        End Function
        
        Public Function InsertarSocioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarSocioAsync
            Return MyBase.Channel.InsertarSocioAsync(oSocioBE)
        End Function
        
        Public Function ActualizarSocio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Boolean Implements LotizadorService.INarhen.ActualizarSocio
            Return MyBase.Channel.ActualizarSocio(oSocioBE)
        End Function
        
        Public Function ActualizarSocioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarSocioAsync
            Return MyBase.Channel.ActualizarSocioAsync(oSocioBE)
        End Function
        
        Public Function EliminarSocio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Boolean Implements LotizadorService.INarhen.EliminarSocio
            Return MyBase.Channel.EliminarSocio(oSocioBE)
        End Function
        
        Public Function EliminarSocioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarSocioAsync
            Return MyBase.Channel.EliminarSocioAsync(oSocioBE)
        End Function
        
        Public Function ObtenerSocioPorCriterio(ByVal oSocioBE As Lotizador.BE.SocioBE) As Lotizador.BE.SocioBE() Implements LotizadorService.INarhen.ObtenerSocioPorCriterio
            Return MyBase.Channel.ObtenerSocioPorCriterio(oSocioBE)
        End Function
        
        Public Function ObtenerSocioPorCriterioAsync(ByVal oSocioBE As Lotizador.BE.SocioBE) As System.Threading.Tasks.Task(Of Lotizador.BE.SocioBE()) Implements LotizadorService.INarhen.ObtenerSocioPorCriterioAsync
            Return MyBase.Channel.ObtenerSocioPorCriterioAsync(oSocioBE)
        End Function
        
        Public Function ObtenerTipoDocumentoPorCriterio(ByVal oSocioBE As Lotizador.BE.TipoDocumentoBE) As Lotizador.BE.TipoDocumentoBE() Implements LotizadorService.INarhen.ObtenerTipoDocumentoPorCriterio
            Return MyBase.Channel.ObtenerTipoDocumentoPorCriterio(oSocioBE)
        End Function
        
        Public Function ObtenerTipoDocumentoPorCriterioAsync(ByVal oSocioBE As Lotizador.BE.TipoDocumentoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.TipoDocumentoBE()) Implements LotizadorService.INarhen.ObtenerTipoDocumentoPorCriterioAsync
            Return MyBase.Channel.ObtenerTipoDocumentoPorCriterioAsync(oSocioBE)
        End Function
        
        Public Function ObtenerVariablePorCriterio(ByVal oVariableBE As Lotizador.BE.VariableBE) As Lotizador.BE.VariableBE() Implements LotizadorService.INarhen.ObtenerVariablePorCriterio
            Return MyBase.Channel.ObtenerVariablePorCriterio(oVariableBE)
        End Function
        
        Public Function ObtenerVariablePorCriterioAsync(ByVal oVariableBE As Lotizador.BE.VariableBE) As System.Threading.Tasks.Task(Of Lotizador.BE.VariableBE()) Implements LotizadorService.INarhen.ObtenerVariablePorCriterioAsync
            Return MyBase.Channel.ObtenerVariablePorCriterioAsync(oVariableBE)
        End Function
        
        Public Function GetDepartamentos() As Lotizador.BE.UbigeoBE() Implements LotizadorService.INarhen.GetDepartamentos
            Return MyBase.Channel.GetDepartamentos
        End Function
        
        Public Function GetDepartamentosAsync() As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE()) Implements LotizadorService.INarhen.GetDepartamentosAsync
            Return MyBase.Channel.GetDepartamentosAsync
        End Function
        
        Public Function GetProvincias(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE() Implements LotizadorService.INarhen.GetProvincias
            Return MyBase.Channel.GetProvincias(oUbigeoBE)
        End Function
        
        Public Function GetProvinciasAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE()) Implements LotizadorService.INarhen.GetProvinciasAsync
            Return MyBase.Channel.GetProvinciasAsync(oUbigeoBE)
        End Function
        
        Public Function GetDistritos(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE() Implements LotizadorService.INarhen.GetDistritos
            Return MyBase.Channel.GetDistritos(oUbigeoBE)
        End Function
        
        Public Function GetDistritosAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE()) Implements LotizadorService.INarhen.GetDistritosAsync
            Return MyBase.Channel.GetDistritosAsync(oUbigeoBE)
        End Function
        
        Public Function GetUbigeo(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE Implements LotizadorService.INarhen.GetUbigeo
            Return MyBase.Channel.GetUbigeo(oUbigeoBE)
        End Function
        
        Public Function GetUbigeoAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE) Implements LotizadorService.INarhen.GetUbigeoAsync
            Return MyBase.Channel.GetUbigeoAsync(oUbigeoBE)
        End Function
        
        Public Function GetUbigeoPorCriterio(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As Lotizador.BE.UbigeoBE Implements LotizadorService.INarhen.GetUbigeoPorCriterio
            Return MyBase.Channel.GetUbigeoPorCriterio(oUbigeoBE)
        End Function
        
        Public Function GetUbigeoPorCriterioAsync(ByVal oUbigeoBE As Lotizador.BE.UbigeoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UbigeoBE) Implements LotizadorService.INarhen.GetUbigeoPorCriterioAsync
            Return MyBase.Channel.GetUbigeoPorCriterioAsync(oUbigeoBE)
        End Function
        
        Public Function InsertarMoneda(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Boolean Implements LotizadorService.INarhen.InsertarMoneda
            Return MyBase.Channel.InsertarMoneda(oMonedaBE)
        End Function
        
        Public Function InsertarMonedaAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarMonedaAsync
            Return MyBase.Channel.InsertarMonedaAsync(oMonedaBE)
        End Function
        
        Public Function ActualizarMoneda(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Boolean Implements LotizadorService.INarhen.ActualizarMoneda
            Return MyBase.Channel.ActualizarMoneda(oMonedaBE)
        End Function
        
        Public Function ActualizarMonedaAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarMonedaAsync
            Return MyBase.Channel.ActualizarMonedaAsync(oMonedaBE)
        End Function
        
        Public Function EliminarMoneda(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Boolean Implements LotizadorService.INarhen.EliminarMoneda
            Return MyBase.Channel.EliminarMoneda(oMonedaBE)
        End Function
        
        Public Function EliminarMonedaAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarMonedaAsync
            Return MyBase.Channel.EliminarMonedaAsync(oMonedaBE)
        End Function
        
        Public Function ObtenerMonedaPorCriterio(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As Lotizador.BE.MonedaBE() Implements LotizadorService.INarhen.ObtenerMonedaPorCriterio
            Return MyBase.Channel.ObtenerMonedaPorCriterio(oMonedaBE)
        End Function
        
        Public Function ObtenerMonedaPorCriterioAsync(ByVal oMonedaBE As Lotizador.BE.MonedaBE) As System.Threading.Tasks.Task(Of Lotizador.BE.MonedaBE()) Implements LotizadorService.INarhen.ObtenerMonedaPorCriterioAsync
            Return MyBase.Channel.ObtenerMonedaPorCriterioAsync(oMonedaBE)
        End Function
        
        Public Function InsertarProyecto(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Boolean Implements LotizadorService.INarhen.InsertarProyecto
            Return MyBase.Channel.InsertarProyecto(oProyectoBE)
        End Function
        
        Public Function InsertarProyectoAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarProyectoAsync
            Return MyBase.Channel.InsertarProyectoAsync(oProyectoBE)
        End Function
        
        Public Function ActualizarProyecto(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Boolean Implements LotizadorService.INarhen.ActualizarProyecto
            Return MyBase.Channel.ActualizarProyecto(oProyectoBE)
        End Function
        
        Public Function ActualizarProyectoAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarProyectoAsync
            Return MyBase.Channel.ActualizarProyectoAsync(oProyectoBE)
        End Function
        
        Public Function EliminarProyecto(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Boolean Implements LotizadorService.INarhen.EliminarProyecto
            Return MyBase.Channel.EliminarProyecto(oProyectoBE)
        End Function
        
        Public Function EliminarProyectoAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarProyectoAsync
            Return MyBase.Channel.EliminarProyectoAsync(oProyectoBE)
        End Function
        
        Public Function ObtenerProyectoPorCriterio(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As Lotizador.BE.ProyectoBE() Implements LotizadorService.INarhen.ObtenerProyectoPorCriterio
            Return MyBase.Channel.ObtenerProyectoPorCriterio(oProyectoBE)
        End Function
        
        Public Function ObtenerProyectoPorCriterioAsync(ByVal oProyectoBE As Lotizador.BE.ProyectoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.ProyectoBE()) Implements LotizadorService.INarhen.ObtenerProyectoPorCriterioAsync
            Return MyBase.Channel.ObtenerProyectoPorCriterioAsync(oProyectoBE)
        End Function
        
        Public Function InsertarUnidadCatastral(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Boolean Implements LotizadorService.INarhen.InsertarUnidadCatastral
            Return MyBase.Channel.InsertarUnidadCatastral(oUnidadCatastralBE)
        End Function
        
        Public Function InsertarUnidadCatastralAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarUnidadCatastralAsync
            Return MyBase.Channel.InsertarUnidadCatastralAsync(oUnidadCatastralBE)
        End Function
        
        Public Function ActualizarUnidadCatastral(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Boolean Implements LotizadorService.INarhen.ActualizarUnidadCatastral
            Return MyBase.Channel.ActualizarUnidadCatastral(oUnidadCatastralBE)
        End Function
        
        Public Function ActualizarUnidadCatastralAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarUnidadCatastralAsync
            Return MyBase.Channel.ActualizarUnidadCatastralAsync(oUnidadCatastralBE)
        End Function
        
        Public Function EliminarUnidadCatastral(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Boolean Implements LotizadorService.INarhen.EliminarUnidadCatastral
            Return MyBase.Channel.EliminarUnidadCatastral(oUnidadCatastralBE)
        End Function
        
        Public Function EliminarUnidadCatastralAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarUnidadCatastralAsync
            Return MyBase.Channel.EliminarUnidadCatastralAsync(oUnidadCatastralBE)
        End Function
        
        Public Function ObtenerUnidadCatastralPorCriterio(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As Lotizador.BE.UnidadCatastralBE() Implements LotizadorService.INarhen.ObtenerUnidadCatastralPorCriterio
            Return MyBase.Channel.ObtenerUnidadCatastralPorCriterio(oUnidadCatastralBE)
        End Function
        
        Public Function ObtenerUnidadCatastralPorCriterioAsync(ByVal oUnidadCatastralBE As Lotizador.BE.UnidadCatastralBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UnidadCatastralBE()) Implements LotizadorService.INarhen.ObtenerUnidadCatastralPorCriterioAsync
            Return MyBase.Channel.ObtenerUnidadCatastralPorCriterioAsync(oUnidadCatastralBE)
        End Function
        
        Public Function InsertarLote(ByVal oLoteBE As Lotizador.BE.LoteBE) As Boolean Implements LotizadorService.INarhen.InsertarLote
            Return MyBase.Channel.InsertarLote(oLoteBE)
        End Function
        
        Public Function InsertarLoteAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarLoteAsync
            Return MyBase.Channel.InsertarLoteAsync(oLoteBE)
        End Function
        
        Public Function ActualizarLote(ByVal oLoteBE As Lotizador.BE.LoteBE) As Boolean Implements LotizadorService.INarhen.ActualizarLote
            Return MyBase.Channel.ActualizarLote(oLoteBE)
        End Function
        
        Public Function ActualizarLoteAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarLoteAsync
            Return MyBase.Channel.ActualizarLoteAsync(oLoteBE)
        End Function
        
        Public Function EliminarLote(ByVal oLoteBE As Lotizador.BE.LoteBE) As Boolean Implements LotizadorService.INarhen.EliminarLote
            Return MyBase.Channel.EliminarLote(oLoteBE)
        End Function
        
        Public Function EliminarLoteAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarLoteAsync
            Return MyBase.Channel.EliminarLoteAsync(oLoteBE)
        End Function
        
        Public Function ObtenerLotePorCriterio(ByVal oLoteBE As Lotizador.BE.LoteBE) As Lotizador.BE.LoteBE() Implements LotizadorService.INarhen.ObtenerLotePorCriterio
            Return MyBase.Channel.ObtenerLotePorCriterio(oLoteBE)
        End Function
        
        Public Function ObtenerLotePorCriterioAsync(ByVal oLoteBE As Lotizador.BE.LoteBE) As System.Threading.Tasks.Task(Of Lotizador.BE.LoteBE()) Implements LotizadorService.INarhen.ObtenerLotePorCriterioAsync
            Return MyBase.Channel.ObtenerLotePorCriterioAsync(oLoteBE)
        End Function
        
        Public Function ObtenerLotesDisponibles(ByVal IdProyecto As String, ByVal IdLote As String) As Lotizador.BE.LoteBE() Implements LotizadorService.INarhen.ObtenerLotesDisponibles
            Return MyBase.Channel.ObtenerLotesDisponibles(IdProyecto, IdLote)
        End Function
        
        Public Function ObtenerLotesDisponiblesAsync(ByVal IdProyecto As String, ByVal IdLote As String) As System.Threading.Tasks.Task(Of Lotizador.BE.LoteBE()) Implements LotizadorService.INarhen.ObtenerLotesDisponiblesAsync
            Return MyBase.Channel.ObtenerLotesDisponiblesAsync(IdProyecto, IdLote)
        End Function
        
        Public Function InsertarSecuencia(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Boolean Implements LotizadorService.INarhen.InsertarSecuencia
            Return MyBase.Channel.InsertarSecuencia(oSecuenciaBE)
        End Function
        
        Public Function InsertarSecuenciaAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarSecuenciaAsync
            Return MyBase.Channel.InsertarSecuenciaAsync(oSecuenciaBE)
        End Function
        
        Public Function ActualizarSecuencia(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Boolean Implements LotizadorService.INarhen.ActualizarSecuencia
            Return MyBase.Channel.ActualizarSecuencia(oSecuenciaBE)
        End Function
        
        Public Function ActualizarSecuenciaAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarSecuenciaAsync
            Return MyBase.Channel.ActualizarSecuenciaAsync(oSecuenciaBE)
        End Function
        
        Public Function EliminarSecuencia(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Boolean Implements LotizadorService.INarhen.EliminarSecuencia
            Return MyBase.Channel.EliminarSecuencia(oSecuenciaBE)
        End Function
        
        Public Function EliminarSecuenciaAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarSecuenciaAsync
            Return MyBase.Channel.EliminarSecuenciaAsync(oSecuenciaBE)
        End Function
        
        Public Function ObtenerSecuenciaPorCriterio(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As Lotizador.BE.SecuenciaBE() Implements LotizadorService.INarhen.ObtenerSecuenciaPorCriterio
            Return MyBase.Channel.ObtenerSecuenciaPorCriterio(oSecuenciaBE)
        End Function
        
        Public Function ObtenerSecuenciaPorCriterioAsync(ByVal oSecuenciaBE As Lotizador.BE.SecuenciaBE) As System.Threading.Tasks.Task(Of Lotizador.BE.SecuenciaBE()) Implements LotizadorService.INarhen.ObtenerSecuenciaPorCriterioAsync
            Return MyBase.Channel.ObtenerSecuenciaPorCriterioAsync(oSecuenciaBE)
        End Function
        
        Public Function InsertarUsuario(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean Implements LotizadorService.INarhen.InsertarUsuario
            Return MyBase.Channel.InsertarUsuario(oUsuarioBE)
        End Function
        
        Public Function InsertarUsuarioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarUsuarioAsync
            Return MyBase.Channel.InsertarUsuarioAsync(oUsuarioBE)
        End Function
        
        Public Function ActualizarUsuario(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean Implements LotizadorService.INarhen.ActualizarUsuario
            Return MyBase.Channel.ActualizarUsuario(oUsuarioBE)
        End Function
        
        Public Function ActualizarUsuarioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarUsuarioAsync
            Return MyBase.Channel.ActualizarUsuarioAsync(oUsuarioBE)
        End Function
        
        Public Function ActualizarPassword(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean Implements LotizadorService.INarhen.ActualizarPassword
            Return MyBase.Channel.ActualizarPassword(oUsuarioBE)
        End Function
        
        Public Function ActualizarPasswordAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarPasswordAsync
            Return MyBase.Channel.ActualizarPasswordAsync(oUsuarioBE)
        End Function
        
        Public Function EliminarUsuario(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Boolean Implements LotizadorService.INarhen.EliminarUsuario
            Return MyBase.Channel.EliminarUsuario(oUsuarioBE)
        End Function
        
        Public Function EliminarUsuarioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarUsuarioAsync
            Return MyBase.Channel.EliminarUsuarioAsync(oUsuarioBE)
        End Function
        
        Public Function ObtenerUsuarioPorCriterio(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As Lotizador.BE.UsuarioBE() Implements LotizadorService.INarhen.ObtenerUsuarioPorCriterio
            Return MyBase.Channel.ObtenerUsuarioPorCriterio(oUsuarioBE)
        End Function
        
        Public Function ObtenerUsuarioPorCriterioAsync(ByVal oUsuarioBE As Lotizador.BE.UsuarioBE) As System.Threading.Tasks.Task(Of Lotizador.BE.UsuarioBE()) Implements LotizadorService.INarhen.ObtenerUsuarioPorCriterioAsync
            Return MyBase.Channel.ObtenerUsuarioPorCriterioAsync(oUsuarioBE)
        End Function
        
        Public Function ObtenerUsuarioPorId(ByVal IdUsuario As Integer) As Lotizador.BE.UsuarioBE Implements LotizadorService.INarhen.ObtenerUsuarioPorId
            Return MyBase.Channel.ObtenerUsuarioPorId(IdUsuario)
        End Function
        
        Public Function ObtenerUsuarioPorIdAsync(ByVal IdUsuario As Integer) As System.Threading.Tasks.Task(Of Lotizador.BE.UsuarioBE) Implements LotizadorService.INarhen.ObtenerUsuarioPorIdAsync
            Return MyBase.Channel.ObtenerUsuarioPorIdAsync(IdUsuario)
        End Function
        
        Public Function InsertarBanco(ByVal oBancoBE As Lotizador.BE.BancoBE) As Boolean Implements LotizadorService.INarhen.InsertarBanco
            Return MyBase.Channel.InsertarBanco(oBancoBE)
        End Function
        
        Public Function InsertarBancoAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarBancoAsync
            Return MyBase.Channel.InsertarBancoAsync(oBancoBE)
        End Function
        
        Public Function ActualizarBanco(ByVal oBancoBE As Lotizador.BE.BancoBE) As Boolean Implements LotizadorService.INarhen.ActualizarBanco
            Return MyBase.Channel.ActualizarBanco(oBancoBE)
        End Function
        
        Public Function ActualizarBancoAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarBancoAsync
            Return MyBase.Channel.ActualizarBancoAsync(oBancoBE)
        End Function
        
        Public Function EliminarBanco(ByVal oBancoBE As Lotizador.BE.BancoBE) As Boolean Implements LotizadorService.INarhen.EliminarBanco
            Return MyBase.Channel.EliminarBanco(oBancoBE)
        End Function
        
        Public Function EliminarBancoAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarBancoAsync
            Return MyBase.Channel.EliminarBancoAsync(oBancoBE)
        End Function
        
        Public Function ObtenerBancoPorCriterio(ByVal oBancoBE As Lotizador.BE.BancoBE) As Lotizador.BE.BancoBE() Implements LotizadorService.INarhen.ObtenerBancoPorCriterio
            Return MyBase.Channel.ObtenerBancoPorCriterio(oBancoBE)
        End Function
        
        Public Function ObtenerBancoPorCriterioAsync(ByVal oBancoBE As Lotizador.BE.BancoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.BancoBE()) Implements LotizadorService.INarhen.ObtenerBancoPorCriterioAsync
            Return MyBase.Channel.ObtenerBancoPorCriterioAsync(oBancoBE)
        End Function
        
        Public Function InsertarContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Boolean Implements LotizadorService.INarhen.InsertarContrato
            Return MyBase.Channel.InsertarContrato(oContratoBE)
        End Function
        
        Public Function InsertarContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarContratoAsync
            Return MyBase.Channel.InsertarContratoAsync(oContratoBE)
        End Function
        
        Public Function ActualizarContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Boolean Implements LotizadorService.INarhen.ActualizarContrato
            Return MyBase.Channel.ActualizarContrato(oContratoBE)
        End Function
        
        Public Function ActualizarContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarContratoAsync
            Return MyBase.Channel.ActualizarContratoAsync(oContratoBE)
        End Function
        
        Public Function EliminarContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Boolean Implements LotizadorService.INarhen.EliminarContrato
            Return MyBase.Channel.EliminarContrato(oContratoBE)
        End Function
        
        Public Function EliminarContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarContratoAsync
            Return MyBase.Channel.EliminarContratoAsync(oContratoBE)
        End Function
        
        Public Function ObtenerContratoPorCriterio(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Lotizador.BE.ContratoBE() Implements LotizadorService.INarhen.ObtenerContratoPorCriterio
            Return MyBase.Channel.ObtenerContratoPorCriterio(oContratoBE)
        End Function
        
        Public Function ObtenerContratoPorCriterioAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.ContratoBE()) Implements LotizadorService.INarhen.ObtenerContratoPorCriterioAsync
            Return MyBase.Channel.ObtenerContratoPorCriterioAsync(oContratoBE)
        End Function
        
        Public Function ObtenerContrato(ByVal oContratoBE As Lotizador.BE.ContratoBE) As Lotizador.BE.ContratoBE Implements LotizadorService.INarhen.ObtenerContrato
            Return MyBase.Channel.ObtenerContrato(oContratoBE)
        End Function
        
        Public Function ObtenerContratoAsync(ByVal oContratoBE As Lotizador.BE.ContratoBE) As System.Threading.Tasks.Task(Of Lotizador.BE.ContratoBE) Implements LotizadorService.INarhen.ObtenerContratoAsync
            Return MyBase.Channel.ObtenerContratoAsync(oContratoBE)
        End Function
        
        Public Function InsertarMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Boolean Implements LotizadorService.INarhen.InsertarMonedaTipoCambio
            Return MyBase.Channel.InsertarMonedaTipoCambio(oMonedaTipoCambio)
        End Function
        
        Public Function InsertarMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarMonedaTipoCambioAsync
            Return MyBase.Channel.InsertarMonedaTipoCambioAsync(oMonedaTipoCambio)
        End Function
        
        Public Function ActualizarMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Boolean Implements LotizadorService.INarhen.ActualizarMonedaTipoCambio
            Return MyBase.Channel.ActualizarMonedaTipoCambio(oMonedaTipoCambio)
        End Function
        
        Public Function ActualizarMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarMonedaTipoCambioAsync
            Return MyBase.Channel.ActualizarMonedaTipoCambioAsync(oMonedaTipoCambio)
        End Function
        
        Public Function EliminarMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Boolean Implements LotizadorService.INarhen.EliminarMonedaTipoCambio
            Return MyBase.Channel.EliminarMonedaTipoCambio(oMonedaTipoCambio)
        End Function
        
        Public Function EliminarMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.EliminarMonedaTipoCambioAsync
            Return MyBase.Channel.EliminarMonedaTipoCambioAsync(oMonedaTipoCambio)
        End Function
        
        Public Function ObtenerMonedaTipoCambio(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As Lotizador.BE.MonedaTipoCambioBE() Implements LotizadorService.INarhen.ObtenerMonedaTipoCambio
            Return MyBase.Channel.ObtenerMonedaTipoCambio(oMonedaTipoCambio)
        End Function
        
        Public Function ObtenerMonedaTipoCambioAsync(ByVal oMonedaTipoCambio As Lotizador.BE.MonedaTipoCambioBE) As System.Threading.Tasks.Task(Of Lotizador.BE.MonedaTipoCambioBE()) Implements LotizadorService.INarhen.ObtenerMonedaTipoCambioAsync
            Return MyBase.Channel.ObtenerMonedaTipoCambioAsync(oMonedaTipoCambio)
        End Function
        
        Public Function CommandText(ByVal oGeneralBE As Lotizador.BE.GeneralBE) As Lotizador.BE.GeneralBE Implements LotizadorService.INarhen.CommandText
            Return MyBase.Channel.CommandText(oGeneralBE)
        End Function
        
        Public Function CommandTextAsync(ByVal oGeneralBE As Lotizador.BE.GeneralBE) As System.Threading.Tasks.Task(Of Lotizador.BE.GeneralBE) Implements LotizadorService.INarhen.CommandTextAsync
            Return MyBase.Channel.CommandTextAsync(oGeneralBE)
        End Function
        
        Public Function ExecuteSQL(ByVal QueryString As String) As System.Data.DataSet Implements LotizadorService.INarhen.ExecuteSQL
            Return MyBase.Channel.ExecuteSQL(QueryString)
        End Function
        
        Public Function ExecuteSQLAsync(ByVal QueryString As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements LotizadorService.INarhen.ExecuteSQLAsync
            Return MyBase.Channel.ExecuteSQLAsync(QueryString)
        End Function
        
        Public Function InsertarListaError(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As Boolean Implements LotizadorService.INarhen.InsertarListaError
            Return MyBase.Channel.InsertarListaError(oListaErrorBE)
        End Function
        
        Public Function InsertarListaErrorAsync(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.InsertarListaErrorAsync
            Return MyBase.Channel.InsertarListaErrorAsync(oListaErrorBE)
        End Function
        
        Public Function ActualizarListaError(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As Boolean Implements LotizadorService.INarhen.ActualizarListaError
            Return MyBase.Channel.ActualizarListaError(oListaErrorBE)
        End Function
        
        Public Function ActualizarListaErrorAsync(ByVal oListaErrorBE As Lotizador.BE.ListaErrorBE) As System.Threading.Tasks.Task(Of Boolean) Implements LotizadorService.INarhen.ActualizarListaErrorAsync
            Return MyBase.Channel.ActualizarListaErrorAsync(oListaErrorBE)
        End Function
    End Class
End Namespace
